services:
  customer:
    build:
      context: .
      dockerfile: docker/flutter_web.Dockerfile
      args:
        APP_DIR: pj_customer
        BASE_URL: ${API_BASE_URL:-http://localhost:8000}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
