services:
  staff:
    build:
      context: .
      dockerfile: docker/flutter_web.Dockerfile
      args:
        APP_DIR: pj_staff
        BASE_URL: http://ltsmapi.45.32.155.226.sslip.io
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
